name: Build
on:
  pull_request:
  push:
    branches:
      - master

jobs:
    runs-on: windows-latest
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4  
      - name: Run a script
        run: .\build.ps1
